export interface Product {
  id: number;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  category: string;
  features: string[];
  status: 'active' | 'beta' | 'coming-soon';
  icon: string;
  pricing: { starter: number; professional: number; enterprise: number };
  demoUrl: string;
}

export const productsData: Product[] = [
  // Automation Products
  {
    id: 1,
    name: 'AutoFlow',
    slug: 'autoflow',
    description: 'Intelligent workflow automation system',
    longDescription: 'AutoFlow is a powerful workflow automation platform designed to streamline your business processes. Automate repetitive tasks, schedule complex workflows, and handle errors gracefully with intelligent retry mechanisms.',
    category: 'Automation',
    features: ['Process automation', 'Scheduled tasks', 'Error handling', 'Custom workflows', 'API integrations', 'Real-time monitoring'],
    status: 'active',
    icon: 'Cog',
    pricing: { starter: 29, professional: 99, enterprise: 299 },
    demoUrl: '/demo/autoflow',
  },
  {
    id: 2,
    name: 'AppointmentPro',
    slug: 'appointmentpro',
    description: 'Smart appointment scheduling and management system',
    longDescription: 'AppointmentPro simplifies appointment booking with calendar integration, automated reminders, and multi-resource scheduling. Perfect for healthcare, salons, consultants, and service-based businesses.',
    category: 'Scheduling',
    features: ['Calendar integration', 'Automated reminders', 'Multi-resource booking', 'Client notifications', 'Payment integration', 'Analytics dashboard'],
    status: 'active',
    icon: 'Calendar',
    pricing: { starter: 49, professional: 149, enterprise: 399 },
    demoUrl: '/demo/appointmentpro',
  },
  {
    id: 3,
    name: 'TradeBotElite',
    slug: 'tradebotelite',
    description: 'Advanced automated trading bot with AI-powered strategies',
    longDescription: 'TradeBotElite leverages machine learning to identify market opportunities and execute trades automatically. With 24/7 monitoring, risk management, and advanced algorithms, maximize your trading efficiency.',
    category: 'Trading',
    features: ['Real-time market analysis', 'Algorithm trading', '24/7 monitoring', 'Risk management', 'Backtesting tools', 'Multiple exchange support'],
    status: 'active',
    icon: 'TrendingUp',
    pricing: { starter: 199, professional: 499, enterprise: 1499 },
    demoUrl: '/demo/tradebotelite',
  },
  {
    id: 4,
    name: 'CryptoBot Pro',
    slug: 'cryptobotpro',
    description: 'Cryptocurrency trading automation platform',
    longDescription: 'CryptoBot Pro is the ultimate solution for cryptocurrency traders. Automate your trading strategy across multiple exchanges with smart signals, portfolio tracking, and advanced analytics.',
    category: 'Trading',
    features: ['Multi-exchange support', 'Portfolio tracking', 'Smart alerts', 'Historical backtesting', 'API integration', 'Risk limit controls'],
    status: 'active',
    icon: 'Coins',
    pricing: { starter: 149, professional: 399, enterprise: 999 },
    demoUrl: '/demo/cryptobotpro',
  },
  {
    id: 5,
    name: 'DataVault',
    slug: 'datavault',
    description: 'Secure data management and analytics platform',
    longDescription: 'DataVault provides enterprise-grade security for your most sensitive data. With end-to-end encryption, real-time analytics, and compliance features, keep your data safe while gaining powerful insights.',
    category: 'Data',
    features: ['Data encryption', 'Real-time analytics', 'Compliance ready', 'Data visualization', 'Automated backups', 'Audit trails'],
    status: 'active',
    icon: 'Lock',
    pricing: { starter: 99, professional: 299, enterprise: 999 },
    demoUrl: '/demo/datavault',
  },
  {
    id: 6,
    name: 'InsightHub',
    slug: 'insighthub',
    description: 'Business intelligence and reporting dashboard',
    longDescription: 'InsightHub transforms raw data into actionable insights. Create custom dashboards, generate predictive analytics, and share reports with your team in real-time.',
    category: 'Data',
    features: ['Custom dashboards', 'Predictive analytics', 'Data export', 'Team collaboration', 'Scheduled reports', 'Advanced filtering'],
    status: 'active',
    icon: 'BarChart3',
    pricing: { starter: 79, professional: 249, enterprise: 749 },
    demoUrl: '/demo/insighthub',
  },
  {
    id: 7,
    name: 'AIAssist',
    slug: 'aiassist',
    description: 'AI-powered assistant for your team',
    longDescription: 'AIAssist is your intelligent team member. Powered by advanced NLP, it understands context, provides smart suggestions, and integrates seamlessly with your existing tools.',
    category: 'AI',
    features: ['Natural language processing', 'Smart suggestions', 'API access', 'Context awareness', 'Multi-language support', 'Custom training'],
    status: 'beta',
    icon: 'Zap',
    pricing: { starter: 49, professional: 149, enterprise: 499 },
    demoUrl: '/demo/aiassist',
  },
  {
    id: 8,
    name: 'ChatGPT Enterprise',
    slug: 'chatgpt-enterprise',
    description: 'Enterprise-grade conversational AI for business',
    longDescription: 'ChatGPT Enterprise brings the power of advanced language models to your organization. With custom training, enterprise security, and unlimited scalability, transform how your team works.',
    category: 'AI',
    features: ['Custom training', 'API integration', 'Enterprise security', 'Advanced analytics', 'Team management', 'Compliance certifications'],
    status: 'active',
    icon: 'MessageSquare',
    pricing: { starter: 299, professional: 799, enterprise: 2999 },
    demoUrl: '/demo/chatgpt-enterprise',
  },
  {
    id: 9,
    name: 'CodeDeploy',
    slug: 'codedeploy',
    description: 'Automated code deployment and versioning',
    longDescription: 'CodeDeploy automates your entire deployment pipeline. From CI/CD to production, manage versions, track changes, and roll back instantly if needed.',
    category: 'DevOps',
    features: ['CI/CD pipeline', 'Version control', 'Rollback support', 'Environment management', 'Deployment history', 'Team permissions'],
    status: 'coming-soon',
    icon: 'Rocket',
    pricing: { starter: 99, professional: 299, enterprise: 999 },
    demoUrl: '/demo/codedeploy',
  },
  {
    id: 10,
    name: 'CloudMonitor',
    slug: 'cloudmonitor',
    description: 'Real-time cloud infrastructure monitoring',
    longDescription: 'CloudMonitor keeps your infrastructure healthy 24/7. Real-time monitoring, intelligent alerts, and actionable insights for optimal performance.',
    category: 'DevOps',
    features: ['System monitoring', 'Alert system', 'Performance optimization', 'Cost tracking', 'Uptime reporting', 'Integration hub'],
    status: 'active',
    icon: 'Radio',
    pricing: { starter: 79, professional: 249, enterprise: 799 },
    demoUrl: '/demo/cloudmonitor',
  },
  {
    id: 11,
    name: 'MarketingMax',
    slug: 'marketingmax',
    description: 'All-in-one marketing automation platform',
    longDescription: 'MarketingMax combines all your marketing tools in one platform. Email campaigns, social media automation, lead scoring, and detailed ROI tracking.',
    category: 'Marketing',
    features: ['Email campaigns', 'Social media automation', 'Lead scoring', 'ROI tracking', 'A/B testing', 'Customer segmentation'],
    status: 'active',
    icon: 'Megaphone',
    pricing: { starter: 149, professional: 449, enterprise: 1299 },
    demoUrl: '/demo/marketingmax',
  },
  {
    id: 12,
    name: 'SEO Optimizer',
    slug: 'seo-optimizer',
    description: 'Advanced SEO tools for search engine optimization',
    longDescription: 'SEO Optimizer gives you the tools to dominate search results. Keyword research, competitor analysis, rank tracking, and comprehensive site audits.',
    category: 'Marketing',
    features: ['Keyword research', 'Competitor analysis', 'Rank tracking', 'Site audits', 'Content optimization', 'Backlink analysis'],
    status: 'active',
    icon: 'Search',
    pricing: { starter: 99, professional: 299, enterprise: 899 },
    demoUrl: '/demo/seo-optimizer',
  },
  {
    id: 13,
    name: 'FinanceFlow',
    slug: 'financeflow',
    description: 'Comprehensive financial management and accounting software',
    longDescription: 'FinanceFlow streamlines your entire financial operation. Invoice management, expense tracking, financial reporting, and tax preparation all in one place.',
    category: 'Finance',
    features: ['Invoice management', 'Expense tracking', 'Financial reporting', 'Tax preparation', 'Recurring billing', 'Multi-currency support'],
    status: 'active',
    icon: 'DollarSign',
    pricing: { starter: 49, professional: 149, enterprise: 499 },
    demoUrl: '/demo/financeflow',
  },
  {
    id: 14,
    name: 'InvestmentAnalyzer',
    slug: 'investmentanalyzer',
    description: 'Investment portfolio analysis and optimization tool',
    longDescription: 'InvestmentAnalyzer helps you make smarter investment decisions. Portfolio tracking, risk analysis, asset allocation, and detailed performance reports.',
    category: 'Finance',
    features: ['Portfolio tracking', 'Risk analysis', 'Asset allocation', 'Performance reports', 'Tax-loss harvesting', 'Rebalancing alerts'],
    status: 'beta',
    icon: 'PieChart',
    pricing: { starter: 99, professional: 299, enterprise: 899 },
    demoUrl: '/demo/investmentanalyzer',
  },
  {
    id: 15,
    name: 'CRMSync',
    slug: 'crmsync',
    description: 'Advanced customer relationship management system',
    longDescription: 'CRMSync centralizes all your customer data. Contact management, sales pipeline tracking, and actionable customer insights in one unified platform.',
    category: 'CRM',
    features: ['Contact management', 'Sales pipeline', 'Customer insights', 'Integration hub', 'Activity tracking', 'Deal management'],
    status: 'active',
    icon: 'Users',
    pricing: { starter: 99, professional: 299, enterprise: 999 },
    demoUrl: '/demo/crmsync',
  },
  {
    id: 16,
    name: 'SupportHub',
    slug: 'supporthub',
    description: 'Multi-channel customer support platform',
    longDescription: 'SupportHub brings all your support channels together. Manage tickets, provide live chat support, maintain a knowledge base, and track team performance.',
    category: 'Support',
    features: ['Ticket management', 'Live chat', 'Knowledge base', 'Team collaboration', 'Customer satisfaction tracking', 'Reporting'],
    status: 'active',
    icon: 'Headphones',
    pricing: { starter: 79, professional: 249, enterprise: 799 },
    demoUrl: '/demo/supporthub',
  },
];

export const categories = [
  'All Products',
  'Automation',
  'Scheduling',
  'Trading',
  'Data',
  'AI',
  'DevOps',
  'Marketing',
  'Finance',
  'CRM',
  'Support',
];

const neutralChip = 'bg-ink-100 text-ink-700 border border-line';

export const categoryColors: Record<string, string> = {
  'Automation': neutralChip,
  'Scheduling': neutralChip,
  'Trading': neutralChip,
  'Data': neutralChip,
  'AI': neutralChip,
  'DevOps': neutralChip,
  'Marketing': neutralChip,
  'Finance': neutralChip,
  'CRM': neutralChip,
  'Support': neutralChip,
};

export const statusColors: Record<string, string> = {
  'active': 'bg-ink-900 text-white border border-ink-900',
  'beta': 'bg-ink-100 text-ink-700 border border-line',
  'coming-soon': 'bg-white text-ink-500 border border-line',
};
